name: Vegear
favicon: null
layout_spectrum: 0.50112
typography_spectrum: 0.30737
title: 'I find vegan cruelty-free brands, apparel, shoes, accesories and more.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4678c1'
    - '#000000'
    - '#31374f'
    - '#e2eaff'
    - '#cda79c'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
